### ISSUE TITLE
Combo: Clear button layout shift in Material/Fluent themes

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-webcomponents#783] opened 2023-06-07 09:22 UTC
## Description  
The combo clear value button triggers an outward shift when a value is selected.
This is reproduceable only in Material/Fluent themes. 

## Steps to reproduce  

See the attached clip.

## Result  
The combo input container expands.

## Expected result  
The presence of the button should not cause the whole input container to expand.

## Attachments  

https://github.com/IgniteUI/igniteui-webcomponents/assets/20106115/d64296af-8026-4f3e-8200-e53143befd84

**Comment by simeonoff** [comment] 2023-06-08 10:25
This is a duplicate of #651. Take a look at the issue I referenced, it's the expected behavior.

**Closed** 2023-06-08 10:31 UTC
Labels: bug, wontfix, severity: low, status: not-a-bug
