### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-webcomponents#176] opened 2021-12-02 14:51 UTC
_Estimated Delivery FEB 22

- [ ] Research
- [ ] Specification
- [ ] Component and tests implementation
- [ ] API Documentation
- [ ] Design implementation

**Comment by gedinakova** [comment] 2021-12-03 12:41
Duplicate of #55

**Comment by gedinakova** [comment] 2021-12-03 12:42
Duplicate of #55

**Closed** 2021-12-07 09:42 UTC
Labels: duplicate, feature
