### ISSUE TITLE
Stepper Sample Issues (in Storybook): some properties are not working or breaking the component visually

### ISSUE THREAD

**Issue by andiesm813** [IgniteUI/igniteui-webcomponents#703] opened 2023-03-15 15:01 UTC
## Description  
**Size Switcher:** changing the size from small to medium or large does not seem to affect the actual component size.

**Title Position**
Changing the positioning to "undefined" seems to be visually breaking the component (see before and after):

![image](https://user-images.githubusercontent.com/86068582/225350000-65303482-258b-4e87-95d4-265909ce297a.png)

## Steps to reproduce  

1. Go to the [stepper sample](https://igniteui.github.io/igniteui-webcomponents/?path=/docs/stepper--basic)
2. Use the size radio group to try the different sizes.
3. Change the title positioning to undefined and take a look at the component.

**Comment by rkaraivanov** [comment] 2023-03-15 16:24
AFAIK the stepper does not support the _**size**_ property by design. At least this is the impression I have by looking at the [specification](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Stepper-Specification) and the [design handoff](https://www.figma.com/file/iBiSKAZJ56Z3Pd0zertjHb/Stepper-Design-Handoff?node-id=0%3A1).

In any case it should be removed as it is misleading to a developer.

As for the `titlePosition` it seems to be a side-effect of Storybook trying to bind `undefined` as a string instead of, well `undefined`. This should be fixed in the SB sample.

@teodosiah 
Can you assign someone to take a look at these issues?

**Closed** 2023-05-05 07:30 UTC
Labels: bug, status: resolved, stepper
