### ISSUE TITLE
adding column in code throws TypeError: e.resetCaches is not a function

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-webcomponents#595] opened 2022-12-22 16:19 UTC
## Description  
cannot add columns in code 

## Steps to reproduce  
code example:
var col = document.createElement("igc-column") as IgcColumnComponent;
   col.field = "LastName"; 
   col.groupable = true; col.sortable=true,col.editable=true,col.filterable=true;col.selectable=true;    
   otherGrid.columns.push(col);

-> run attached sample and press add column button

## Result  
column is not displayed in grid and error is in console:
ERROR TypeError: e.resetCaches is not a function
    at combined.js:75:140653
    at Array.forEach (<anonymous>)
    at cl.resetColumnsCaches (combined.js:75:140640)
    at cl.resetCaches (combined.js:75:141546)
    at cl.calculateGridSizes (combined.js:76:12365)
    at cl.ngDoCheck (combined.js:75:146904)
    at cl.ngDoCheck (combined.js:77:9921)
    at oY (combined.js:11:8836)
    at _F (combined.js:11:8603)
    at hx (combined.js:11:8282)

## Expected result  
column is added to grid without exception and displays data

## Attachments  
[grid-wc.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10288456/grid-wc.zip)

**Comment by skrustev** [comment] 2023-02-27 14:06
This doesn't seem to be an issues with the grid itself but rather limitation on how web components can be modified. An `IgcColumnComponent` can be created manually only through the template using the syntax:

```html
<igc-column field="LastName" header="LastName" >
</igc-column>
```

If a user would like to add a column through code according to the latest changes, he would need to user the columns setter that accepts actually `IgxColumn[]` and not `IgxColumnComponent[]`. Its currently is a bit confusing for me though, because the getter has return type `IgxColumnComponent[]` :

```typescript
grid.columns = [
    { field: 'ID', groupable: true, sortable: true, editable: true, filterable: true, selectable: true },
    { field: 'FirstName', groupable: true, sortable: true, editable: true, filterable: true, selectable: true },
    { field: 'LastName', groupable: true, sortable: true, editable: true, filterable: true, selectable: true }
]
```

@damyanpetev Is that correct? Maybe it would be a good idea to add a `columns` getter of some sort that returns the current column config without the need to redefine the same columns they have defined in the template or this is expected?


For some reason the latest typings state but maybe that's a separate issue or maybe they are outdated?:
```typescript
public set columns(value: IgcColumnComponent[]);
```

**Comment by skrustev** [comment] 2023-03-07 07:38
Closing this since it is not a bug actually. If there are any improvements that need to be addressed, it will be done separately. I've logged the issues regarding the definitions here: IgniteUI/igniteui-angular/issues/12725

**Closed by skrustev** 2023-03-07 07:38 UTC
Labels: bug, status: not-a-bug
