### ISSUE TITLE
[Bug]: Checked fluent radio in Gecko based browsers is not rendered consistently

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-webcomponents#1510] opened 2024-12-06 10:27 UTC
### Which component(s) are affected?

Radio & Radio Group

### Description

Gecko based browsers
![image](https://github.com/user-attachments/assets/b6f53dbc-cfa3-4d5d-86c6-75cc44921f83)

Other browsers
![image](https://github.com/user-attachments/assets/45cc8311-f485-4d60-9796-8beeb4ec1d32)

### Reproduction

1. Create a radio group and open the page in Gecko based browser
2. Check a radio from the group
3. Observe

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

5.1.2

### Browser/OS/Node environment

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"

**Comment by simeonoff** [comment] 2024-12-13 12:58
Closing as the issue is probably related to https://github.com/asyncLiz/rollup-plugin-minify-html-literals/issues/35

**Closed by simeonoff** 2024-12-13 12:58 UTC
Labels: bug, radio, radio-group, severity: low, fluent-theme, :eyes: status: in-review, status: third-party-issue, firefox
