### ISSUE TITLE
igc-combo clearing selection through the clear button does not clear the list selection

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-webcomponents#652] opened 2023-02-03 14:56 UTC
## Description  
I get a warning when clearing selection via the clear button and the selection in the list stays and only the input is cleared.

## Steps to reproduce  

1. Create an app builder app with a combo.
2. Generate the app for Web Components
3. Open the combo and select a few items
4. Press the clear button

## Result  
The input is cleared, but the list items stay selected.

## Expected result  
The combo items should get deselected.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/216633650-d970f897-e5a6-4cb8-9d19-ee58c540eef3.png)
![image](https://user-images.githubusercontent.com/1472513/216633770-487fdea0-8baa-4713-aa0b-488b87575002.png)

**Comment by simeonoff** [comment] 2023-02-06 08:08
@kdinev Seems like the app builder uses an old version of the package (4.1.0). This issue has been resolved in 4.2.1. I tested by downloading a web components app generated by the app builder that has a combo in it. After updating the igniteui-webcomponents package to the latest version, the issue is no longer present.

**Closed** 2023-02-06 08:38 UTC
Labels: bug, status: resolved, severity: high, combo
