### ISSUE TITLE
Restoring Template Columns

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#1099] opened 2024-03-11 16:18 UTC
## Description  
Cannot restore column templates as seen in Angular
eg.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence#restoring-columns

https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/state-persistence
https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/state-persistence

## Steps to reproduce  

1. [Step 1](https://codesandbox.io/p/sandbox/competent-rhodes-pdf9kn)
2. Move a column
3. Click Save
4. Move another column
5. Click Restore

## Result  
The contact name field reverts back to its data item values
## Expected result  
The contact name field remains intact how it was originally seen on startup

**Comment by mddifilippo89** [comment] 2024-03-12 17:55
@dkamburov This is a blocker for some folks. Any sort of workaround/explanation and timeframe would be greatly appreciated.

**Comment by dkamburov** [comment] 2024-03-13 09:33
@mddifilippo89 Yes, the issue related to this one is logged here - https://github.com/IgniteUI/igniteui-angular/issues/13659
We can rise it's priority, but I'm not sure if it will make it for the upcoming release, maybe the next one.

**Comment by vipulanand-nirvanasolutions** [comment] 2024-04-02 20:43
@dkamburov Any time frame regarding to solution of this issue? This is a critical issue for us any workaround would be greatly appreciated.

**Comment by dkamburov** [comment] 2024-04-03 07:00
@vipulanand-nirvanasolutions I'm adding the issue for the next sprint, hopefully we'll be able to work on it in the next two weeks.

**Comment by vipulanand-nirvanasolutions** [comment] 2024-04-25 13:39
Any updates? Hopefully, this issue has been picked for the new Infragistics release.

**Comment by dkamburov** [comment] 2024-05-07 10:43
Hello @vipulanand-nirvanasolutions,
Thank you for your patience. We're still working on resolving the issue, and it remains a priority for us. Please stay tuned for updates regarding a fix to be included in the upcoming release.

**Comment by bharatjangir-nirvanasolutions** [comment] 2024-05-21 10:49
Hi @dkamburov, 

I see that this issue (#1099) pertains to Angular. However, I want to update you that we are expecting a solution for React as well. I hope this is being addressed within this issue.

I understand that this is a high-priority task for your team, but I would like to know the release date so we can plan to incorporate the new React grid in our upcoming version.

**Comment by jainankit2474** [comment] 2024-07-26 18:10
What's the update on this issue? When can we expect a fix on this?

**Comment by dkamburov** [comment] 2024-07-29 12:16
It's actually a bigger issue than expected, we are currently discussing how this can be handled within the team.

**Comment by avanish-srivastava** [comment] 2024-10-10 08:08
Hi @dkamburov 

I hope you're doing well. I wanted to follow up on the status of the issue, as it has been open for some time now. Could you please provide an update or share any expected timeline for its resolution? Additionally, could you confirm in which upcoming Infragistics update we might expect to see the fix?

Looking forward to your response.

**Comment by dkamburov** [comment] 2024-10-10 08:24
@avanish-srivastava we already have a [fix](https://github.com/IgniteUI/igniteui-angular/pull/14762), you can follow it to see when it's merged. We're planning a release for Webcomponents grids this week and this won't make it unfortunately, but we'll make sure to push it in in the next one. Probably two or three weeks from now.

**Comment by avanish-srivastava** [comment] 2024-10-10 08:29
@dkamburov Can we expect this change in IgrGrid as well in next two or three weeks from now?

**Comment by dkamburov** [comment] 2024-10-10 08:32
Yes

**Comment by vipulanand-nirvanasolutions** [comment] 2024-10-22 18:16
Hi @dkamburov,

I hope you're doing well. I wanted to know if the fix has been deployed in the latest patch for **IgrGrid.** We are following this item closely as this is a crucial functionality for our product. Also, we have to further communicate the timeline as we are planning to incorporate the new Infragistic React grid in our upcoming version. Hence, a confirmed timeline would be greatly appreciated.

**Comment by vipulanand-nirvanasolutions** [comment] 2024-10-25 07:41
@dkamburov any updates?

**Comment by avanish-srivastava** [comment] 2024-10-25 13:04
Hi @dkamburov 

I wanted to follow up on this issue. You mentioned that the fix was expected to be merged in the new version within two weeks. Since that timeframe has passed, could you provide an update on when we can expect this fix to be merged?

Thanks in advance for your response!

**Comment by vipulanand-nirvanasolutions** [comment] 2024-11-11 09:26
Hi @dkamburov 

I wanted to follow up on our last conversation, as it has been two weeks, but we don't know whether the new version has been released or not.

**Comment by vipulanand-nirvanasolutions** [comment] 2024-11-12 07:39
> > Hi @dkamburov
> > I wanted to follow up on this issue. You mentioned that the fix was expected to be merged in the new version within two weeks. Since that timeframe has passed, could you provide an update on when we can expect this fix to be merged?
> > Thanks in advance for your response!
> 
> Hi @avanish-srivastava, we had some delays for our internal releases, the current estimate is to have the release in the current sprint so hopefully it will be out in the next two weeks.

Hi @dkamburov

I wanted to follow up on our last conversation, as it has been two weeks, but we don't know whether the new version has been released or not.

**Comment by dkamburov** [comment] 2024-11-12 10:24
@vipulanand-nirvanasolutions we are working on publishing the latest official version, we've just published a [beta](https://www.npmjs.com/package/igniteui-webcomponents-grids/v/5.0.3-beta.0) you can check out the fix for it is available in the package.
Stay tuned the official 5.1.0 should be out in the next days. Thanks for your patience!

**Comment by vipulanand-nirvanasolutions** [comment] 2024-12-05 07:49
> @vipulanand-nirvanasolutions we are working on publishing the latest official version, we've just published a [beta](https://www.npmjs.com/package/igniteui-webcomponents-grids/v/5.0.3-beta.0) you can check out the fix for it is available in the package. Stay tuned the official 5.1.0 should be out in the next days. Thanks for your patience!

Hi @dkamburov,

I can see Ignite UI for React has released the latest 18.7.4 version. Will the issue mentioned here be resolved in that version?
Also, I have verified the changelog for the same but haven't found any changes for that version.

**Comment by dkamburov** [comment] 2024-12-05 13:43
@vipulanand-nirvanasolutions The fix is included in the latest release of react, the bug fixes are not usually included into the changelogs. We are now retaining the templates so you don't have to restore the template of the columns anymore, they will be restored out of the box now.

**Closed by dkamburov** 2024-12-05 13:43 UTC
Labels: bug, :hammer_and_wrench: status: in-development
