### ISSUE TITLE
IgcDatePicker's dropdown calendar shows behind IgcDialog

### ISSUE THREAD

**Issue by IG-Mori** [IgniteUI/igniteui-webcomponents#755] opened 2023-04-27 07:54 UTC
## Description  
IgcDatePicker's dropdown calendar shows behind IgcDialog.
IgcDatePicker cannot select dates.

It was found on Blazor and is being discussed in the following threads
https://my.slingshotapp.io/openTopic/e97e10ef_b3d53c0d-84d0-46b4-8a68-abb3d9396dc9

## Steps to reproduce  

1. Launch the attached application.
2. Click "Show Dialog" button.
3. When the dialog appears, click on the DatePicker's calendar icon.

## Result  
The calendar is displayed behind the dialog.
The calendar date cannot be selected.

## Expected result  
The calendar is displayed in a position that does not overlap the dialog.
The calendar allows the date to be selected.

## Attachments  
[C-00229971-igc-dialog-and-datepicker.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/11340966/C-00229971-igc-dialog-and-datepicker.zip)

**Comment by jsakamotoIGJP** [comment] 2023-04-27 08:11
### Supplement

After extracting the attached Zip file to a working folder, the `npm ci` and `npm start` commands can be executed in the working folder to reproduce the problem as shown below.

![image](https://user-images.githubusercontent.com/102948935/234800004-f5f9a7f5-5e30-4f35-93bc-3657299feaf4.png)

**Comment by simeonoff** [comment] 2023-05-09 08:44
@IG-Mori There's little we can do about it. The `igc-dialog` component uses the native dialog element internally. The native dialog element renders all of its content in the [Top Layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer). Since the Date Picker renders its dropdown in an absolutely positioned element outside the shadow root of the`igc-dialog` component, its content will always remain covered.

**Comment by IG-Mori** [comment] 2023-05-10 04:58
@simeonoff 
Hi Simeon
Thanks for your comment. I would tell the client as a constraint that the combination of `IgcDatePicker` and `IgcDialog` is not available.

**Comment by simeonoff** [comment] 2023-05-10 06:29
@IG-Mori This should be solved on the side of the date picker component in my opinion.

**Comment by IG-Mori** [comment] 2023-05-10 06:36
@simeonoff 
I am of the same opinion.
Could you suggest this problem on the daypicker side? :)

**Comment by simeonoff** [comment] 2023-05-10 07:54
Yes, if the date picker component were to project its dropdown content inside the component's template, then it will work with the igc-dialog component.

**Comment by IG-Mori** [comment] 2023-05-11 02:11
@simeonoff 
Hi Simeon
Has an investigation been initiated on the DatePicker side?
Do I need to register a new issue?

**Comment by simeonoff** [comment] 2023-05-12 10:33
The Date Picker component in question is not a part of this repo. There's another team in Infragistics responsible for it. @gmurray81 can you chime in on the issue and whether this will ever be resolved in the other web components package?

**Comment by gmurray81** [comment] 2023-05-12 10:43
I don't think we'd be averse to altering the way the date picker requests the floating content. We didn't see this issue over here. @ig-robstoffers if you could investigate when time permits since you were just in the popup.

**Comment by gmurray81** [comment] 2023-05-12 11:22
I'm not entirely sure whether dialog would nest well though, and showPopover is experimental and not available in all browsers yet.... Anyhow we can see if something can be done. But maybe Dialog should also consider a display mode that doesn't preclude it's content having floating content also?

**Comment by gmurray81** [comment] 2023-05-12 11:36
Simplest solution may be if we are currently joining the popover content to the page root or something, there should be a mode where it is parented by the date picker. This would presumably keep it projected within popup component so that it is hosted in the top layer

**Comment by IG-Mori** [comment] 2023-05-29 07:43
@ig-robstoffers 
Hi, Robert
What is the status of the investigation into this matter?
I want to let my clients know what's going on. :)

**Comment by ig-robstoffers** [comment] 2024-01-16 17:43
The root cause of the issue was a bad interaction between the `igc-dialog` rendering as a top layer component and the calendar dropdown. The calendar dropdown is treated as a completely separate DOM element from the date picker and is a child of the `<body>` element. Because it is not a child of the date picker and the dialog is a top layer component it renders behind the dialog.

To fix this I added new properties to `igc-date-picker` to allow users to configure the dropdown behavior.  If you know that your expected browsers support the [popover](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) API then you can simply set the `UseTopLayer` property to true.

```html
<igc-date-picker use-top-layer="true">
```

Otherwise you can set a combination of `OpenAsChild` and `IsFixed`.  `OpenAsChild` will treat the dropdown as a direct child of the date picker.  If you set this to true the dropdown will open inside of the dialog as you expect, however the dropdown will be clipped by the edges of the dialog.  This might be ok if your dialog is big enough to accomodate the dropdown.  If you want the dropdown to extend outside the dialog bounds then you need to set `IsFixed`.

```html
<igc-date-picker open-as-child="true" is-fixed="true">
```

**Closed by ig-robstoffers** 2024-01-16 17:43 UTC
Labels: bug, wontfix, severity: high, status: third-party-issue
