### ISSUE TITLE
Calendar locale should change the week start day

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-webcomponents#1031] opened 2024-01-17 19:41 UTC
## Description  
In igniteUI for angular changing the locale of the calendar from EN to BG changes the week start day to monday.
Since the week start day i usually part of the locale I believe that here we should have the same behavior.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rkaraivanov** [comment] 2024-01-18 08:14
Duplicate of #1020 
Move any further discussion there as I'm closing this one.

**Closed by rkaraivanov** 2024-01-18 08:14 UTC
Labels: duplicate, question, :new: status: new
