### ISSUE TITLE
Toggle component

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-webcomponents#187] opened 2021-12-02 15:05 UTC
_Estimated Delivery Sprint - TBD

- [ ] Research
- [ ] Specification
- [ ] Component and tests implementation
- [ ] API Documentation
- [ ] Design implementation

**Comment by gedinakova** [comment] 2021-12-03 12:39
Duplicate of #54

**Closed** 2021-12-07 09:42 UTC
Labels: duplicate, feature
